name: Check CODEOWNERS

on: pull_request
jobs:
  build:
    runs-on: ${{ vars.ACTIONS_RUNNER }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: install yq
        run: |
          sudo snap install yq

      - name: generate CODEOWNERS
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS

      - name: check CODEOWNERS for modifications
        run: |
          git diff --exit-code
