name: Check CODEOWNERS

on: pull_request
jobs:
  build:
    runs-on: ${{ vars.ACTIONS_RUNNER }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: install yq
        run: |
          sudo snap install yq

      - name: generate CODEOWNERS
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS

      - name: check CODEOWNERS for modifications
        run: |
          git diff --exit-code

      - name: Push metrics
        if: always()
        continue-on-error: true
        uses: perimeter-81/actions/actions/monitoring/push_metrics@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

